# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Miko Ademagic'
tagline:             'UI Dev, Sydney'
description:         'A Front End/UI Developer from Sydney Australia. Currently working his magic for <a href="http://www.bigcommerce.com">Bigcommerce</a>'
url:                 miko.ademagic.com
baseurl:             /
paginate:            5
paginate_path:       "blog/"

# About/contact
author:
  name:              Miko Ademagic
  url:               https://miko.ademagic.com
  email:             miko@ademagic.com

# Custom vars
version:             1.0.0
